name: uber_eats_clone_2k22
version: 1.0.0+1
publish_to: none
description: Uber eats clone
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  google_place: ^0.4.3
  flutter_dotenv: ^5.0.2
  flutter_typeahead: ^3.2.4
  emojis: ^0.9.9
  lottie: ^1.2.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/icons/
    - assets/images/